{"original_code": "@patch(\"rio_tiler.io.rasterio.rasterio\")\ndef test_tile_outside_bounds_error(rio, app):\n    \"\"\"raise 404 when tile is not found.\"\"\"\n    rio.open = mock_rasterio_open\n\n    response = app.get(\"/cog/tiles/15/0/0?url=https://myurl.com/cog.tif&rescale=0,1000\")\n    assert response.status_code == 404\n    assert response.headers[\"Cache-Control\"] == \"private, max-age=3600\""}