{"original_code": "    async def user_token_exception_handler(\n        request: Request, exc: custom_exc.TokenAuthError\n    ):\n        \"\"\"\n        \u7528\u6237token\u5f02\u5e38\n        :param request:\n        :param exc:\n        :return:\n        \"\"\"\n        logger.error(\n            f\"\u7528\u6237\u8ba4\u8bc1\u5f02\u5e38\\nURL:{request.method}{request.url}\\nHeaders:{request.headers}\\n{traceback.format_exc()}\"\n        )\n\n        return resp.fail(resp.DataNotFound.set_msg(exc.err_desc))"}