{"original_code": "    async def user_not_found_exception_handler(\n        request: Request, exc: custom_exc.AuthenticationError\n    ):\n        \"\"\"\n        \u7528\u6237\u6743\u9650\u4e0d\u8db3\n        :param request:\n        :param exc:\n        :return:\n        \"\"\"\n        logger.error(f\"\u7528\u6237\u6743\u9650\u4e0d\u8db3 \\nURL:{request.method}{request.url}\")\n        return resp.fail(resp.PermissionDenied)"}